PAGES = [
    {
        "name": "Home",
        "url": "/",
        "description": "Homepage with website overview",
        "keywords": ["home", "main", "index", "homepage"],
    },
    {
        "name": "About Us",
        "url": "/about",
        "description": "Learn about our company and team",
        "keywords": ["about", "company", "team", "story", "who we are"],
    },
    {
        "name": "Contact",
        "url": "/page/contact-us",
        "description": "Get in touch with us",
        "keywords": ["contact", "reach", "support", "help", "phone", "email"],
    },
    {
        "name": "Products",
        "url": "/products",
        "description": "Browse our product catalog",
        "keywords": ["products", "catalog", "shop", "store", "items"],
    },
    {
        "name": "Login",
        "url": "/login",
        "description": "Access your account - sign in to view orders, track shipments, and manage your profile",
        "keywords": [
            "login",
            "sign in",
            "signin",
            "access",
            "account",
            "log in",
            "authenticate",
            "enter",
        ],
    },
    {
        "name": "Register",
        "url": "/register",
        "description": "Create a new account - join us to start shopping, save favorites, and track your orders",
        "keywords": [
            "register",
            "sign up",
            "signup",
            "create account",
            "join",
            "new account",
            "membership",
            "enroll",
        ],
    },
    {
        "name": "Blog",
        "url": "/blog",
        "description": "Latest news and articles",
        "keywords": ["blog", "news", "articles", "updates", "posts"],
    },
    {
        "name": "Shipping Informations",
        "url": "/page/shipping-info",
        "description": "Complete guide to our shipping options, delivery times, costs, and international shipping policies",
        "keywords": [
            "shipping",
            "delivery",
            "shipping info",
            "shipping policy",
            "delivery options",
            "shipping costs",
            "shipping rates",
            "international shipping",
            "shipping time",
        ],
    },
    {
        "name": "Refund Policy",
        "url": "/page/refund-policy",
        "description": "Learn about our hassle-free return and refund process, including eligibility, timeframes, and how to request refunds",
        "keywords": [
            "refund",
            "return",
            "refund policy",
            "money back",
            "return policy",
            "refund process",
            "exchange",
            "returns",
        ],
    },
    {
        "name": "delivery Policy",
        "url": "/page/delivery-policy",
        "description": "Detailed information about our delivery process, timeframes, tracking, and what to expect when your order arrives",
        "keywords": [
            "delivery",
            "delivery policy",
            "delivery time",
            "delivery process",
            "package delivery",
            "delivery schedule",
            "delivery tracking",
            "order delivery",
        ],
    },
    {
        "name": "Terms of service",
        "url": "/page/terms-of-service",
        "description": "Read our complete terms of service, user agreements, legal conditions, and policies governing your use of our website",
        "keywords": [
            "terms",
            "terms of service",
            "user agreement",
            "legal",
            "conditions",
            "terms and conditions",
            "website terms",
            "service agreement",
            "policy",
        ],
    },
    {
        "name": "Frequently asked questions",
        "url": "/page/faq",
        "description": "Find answers to the most commonly asked questions about our products, shipping, returns, payments, and customer service",
        "keywords": [
            "faq",
            "frequently asked questions",
            "help",
            "support",
            "questions",
            "answers",
            "common questions",
            "customer help",
            "assistance",
        ],
    },
]
